### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by youngjae41** [USTC-AIS-Lab/PE-Planner#3]
Thank you for sharing the excellent code.

1. Could you provide the methods for operating this on an actual drone?
2. Is it possible to receive instructions on how to build and install this without using Docker?
3. Also, I'm curious if it will still work properly even if the map size increases.

**Comment by kuguao** [comment]
#### 1. Deployment requires the following things (assuming the flight control unit is a PX4):
- [ ] Modify PE-Planner's interface related to the flight controller (modules/px4_interface/px4_interface.hpp) to enable PE-Planner to obtain position estimates and control the UAV. In general, just set the parameter topic_prefix of the Px4Interface constructor to null, i.e. "".
- [ ] Use a motion capture system or laser odometer to provide an accurate position estimate for the PX4.
- [ ] Set up obstacles in the environment and provide the PE-Planner with a correct map of the environment.
**Note**: If you need experimental code, you can contact me (jiaxinqiu@mail.ustc.edu.cn).
#### 2. If you only need PE-Planner, you can just clone the project and execute build.sh to compile the project. If you need to run the simulation, it is recommended to use the provided container. Deploying and configuring the simulation environment is a bit more complicated.
#### 3. If the map is larger, it takes more time to calculate the ESDF when PE-Planner is started.

**Comment by youngjae41** [comment]
I have sent the email. Thank you.
